#!/bin/bash

#****************************************************************
# log into Azure CLI and GitHub CLI before running this script, define your GITHUB_REPO too
# az login
# gh auth login
# export GITHUB_REPO="your/reponame"
#****************************************************************

# Export Azure Subsciription ID
export AZURE_SUBSCRIPTION_ID=$(az account show --query id --output tsv)
echo "Azure Subscription ID: $AZURE_SUBSCRIPTION_ID"

#****************************************************************
# Unhash this section if you need to create a new Service Principal for Github.
# If you have a Service Principal for GitHub already, go to the next section.
# Export variables for GitHub Service Principal
#SP=$(az ad sp create-for-rbac \
#  --name github-terraform \
#  --role contributor \
#  --scopes /subscriptions/$AZURE_SUBSCRIPTION_ID \
#  -o json)
#
#export AZURE_CLIENT_ID=$(echo $SP | jq -r .appId)
#echo "Azure Client ID: $AZURE_CLIENT_ID"
#
#export AZURE_CLIENT_SECRET=$(echo $SP | jq -r .password)
#echo "Azure Client Secret: $AZURE_CLIENT_SECRET"
#
#export AZURE_TENANT_ID=$(echo $SP | jq -r .tenant)
#echo "Azure Tenant ID: $AZURE_TENANT_ID"
#
# Be sure to fill out your GitHub repo in the "subject" field!
#az ad app federated-credential create \ 
#  --id $AZURE_CLIENT_ID \
#  --parameters '{
#    "name": "github-actions-terraform-oidc",
#    "issuer": "https://token.actions.githubusercontent.com",
#    "subject": "repo:dalenfree/azure-resume-challenge-terraform:ref:refs/heads/main", 
#    "description": "GitHub Actions OIDC for main branch deployments",
#    "audiences": ["api://AzureADTokenExchange"]
#  }'
#****************************************************************

#****************************************************************
# If you already have a Service Principal for Github set up, export the AZURE_CLIENT_ID and AZURE_TENANT_ID first
#export AZURE_CLIENT_ID=<Your Client ID for GH SP>
#export AZURE_TENANT_ID=<Your Tenant ID>
#****************************************************************

# Export variables to be used locally and/or in GitHub Secrets. The --query strings match the values included in Terraform setup.
export RESOURCE_GROUP_NAME=$(az group list --query "[?starts_with(name, 'tfresume')].name | [0]" -o tsv)
echo "Resource Group Name: $RESOURCE_GROUP_NAME"

export FUNCTIONAPP_NAME=$(az functionapp list \
  --resource-group $RESOURCE_GROUP_NAME \
  --query "[?starts_with(name, 'fa')].name | [0]" \
  -o tsv)
echo "Function App Name: $FUNCTIONAPP_NAME"

export ACCOUNT_NAME=$(az storage account list \
  --resource-group $RESOURCE_GROUP_NAME \
  --query "[?starts_with(name, 'frontend')].name" \
  -o tsv)
echo "Frontend Storage Account Name: $ACCOUNT_NAME"

export FRONTDOOR_PROFILE=$(az afd profile list \
  --resource-group $RESOURCE_GROUP_NAME \
  --query "[?starts_with(name, 'fdprofile')].name | [0]" -o tsv)
echo "Front Door Profile Name: $FRONTDOOR_PROFILE"

export FRONTDOOR_ENDPOINT=$(az afd endpoint list \
  --profile-name $FRONTDOOR_PROFILE \
  --resource-group $RESOURCE_GROUP_NAME \
  --query "[].hostName" -o tsv)
echo "Front Door Endpoint Hostname: $FRONTDOOR_ENDPOINT"

export FRONTDOOR_ENDPOINT_NAME=$(az afd endpoint list \
  --profile-name $FRONTDOOR_PROFILE \
  --resource-group $RESOURCE_GROUP_NAME \
  --query "[0].name" \
  -o tsv)
echo "Front Door Endpoint Name: $FRONTDOOR_ENDPOINT_NAME"

# Export Cosmos DB variables

export COSMOS_ACCOUNT_NAME=$(az cosmosdb list \
  --resource-group $RESOURCE_GROUP_NAME \
  --query "[?starts_with(name, 'cdb')].name" \
  -o tsv)
echo "Cosmos DB Account Name: $COSMOS_ACCOUNT_NAME"

export COSMOS_DB_ENDPOINT=$(az cosmosdb show \
  --name $COSMOS_ACCOUNT_NAME \
  --resource-group $RESOURCE_GROUP_NAME \
  --query documentEndpoint \
  -o tsv)
echo "Cosmos DB Endpoint: $COSMOS_DB_ENDPOINT"

export COSMOS_DB_KEY=$(az cosmosdb keys list \
  --name $COSMOS_ACCOUNT_NAME \
  --resource-group $RESOURCE_GROUP_NAME \
  --type keys \
  --query "primaryMasterKey" -o tsv)
echo "Cosmos DB Key: $COSMOS_DB_KEY"

export COSMOS_DB_DATABASE_NAME=$(az cosmosdb sql database list \
  --resource-group $RESOURCE_GROUP_NAME \
  --account-name $COSMOS_ACCOUNT_NAME \
  --query "[0].name" -o tsv)
echo "Cosmos DB Database Name: $COSMOS_DB_DATABASE_NAME"

export COSMOS_DB_CONTAINER_NAME=$(az cosmosdb sql container list \
  --resource-group $RESOURCE_GROUP_NAME \
  --account-name $COSMOS_ACCOUNT_NAME \
  --database-name $COSMOS_DB_DATABASE_NAME \
  --query "[0].name" -o tsv)
echo "Cosmos DB Container Name: $COSMOS_DB_CONTAINER_NAME"



# Set all Variables as GitHub Secrets
gh secret set AZURE_CLIENT_ID --body "$AZURE_CLIENT_ID" --repo $GITHUB_REPO
#gh secret set AZURE_CLIENT_SECRET --body "$AZURE_CLIENT_SECRET" --repo $GITHUB_REPO
gh secret set AZURE_TENANT_ID --body "$AZURE_TENANT_ID" --repo $GITHUB_REPO
gh secret set AZURE_SUBSCRIPTION_ID --body "$AZURE_SUBSCRIPTION_ID" --repo $GITHUB_REPO
gh secret set RESOURCE_GROUP_NAME --body "$RESOURCE_GROUP_NAME" --repo $GITHUB_REPO
gh secret set FUNCTIONAPP_NAME --body "$FUNCTIONAPP_NAME" --repo $GITHUB_REPO
gh secret set ACCOUNT_NAME --body "$ACCOUNT_NAME" --repo $GITHUB_REPO
gh secret set FRONTDOOR_PROFILE --body "$FRONTDOOR_PROFILE" --repo $GITHUB_REPO
gh secret set FRONTDOOR_ENDPOINT --body "$FRONTDOOR_ENDPOINT" --repo $GITHUB_REPO
gh secret set COSMOS_DB_ENDPOINT --body "$COSMOS_DB_ENDPOINT" --repo $GITHUB_REPO
gh secret set COSMOS_DB_KEY --body "$COSMOS_DB_KEY" --repo $GITHUB_REPO
gh secret set COSMOS_DB_DATABASE_NAME --body "$COSMOS_DB_DATABASE_NAME" --repo $GITHUB_REPO
gh secret set COSMOS_DB_CONTAINER_NAME --body "$COSMOS_DB_CONTAINER_NAME" --repo $GITHUB_REPO  
gh secret set FRONTDOOR_ENDPOINT_NAME --body "$FRONTDOOR_ENDPOINT_NAME" --repo $GITHUB_REPO   